// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtrhhgKI3ahLe5KXJl9Pn0qagrzZ2-3Y',
    appId: '1:728265546246:web:71444fc4f1837fcec4c187',
    messagingSenderId: '728265546246',
    projectId: 'tupension-e8dae',
    authDomain: 'tupension-e8dae.firebaseapp.com',
    databaseURL: 'https://tupension-e8dae-default-rtdb.firebaseio.com',
    storageBucket: 'tupension-e8dae.appspot.com',
    measurementId: 'G-G0C300LLXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5TJOwiPLDO3kcBSZKvWQLsKAEe0QRn6g',
    appId: '1:728265546246:android:c9a292e47220cd3ac4c187',
    messagingSenderId: '728265546246',
    projectId: 'tupension-e8dae',
    databaseURL: 'https://tupension-e8dae-default-rtdb.firebaseio.com',
    storageBucket: 'tupension-e8dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6vGlLKlFGCBj3iZkf0OIdh0DXMEFqOFQ',
    appId: '1:728265546246:ios:c3e821f8104ef563c4c187',
    messagingSenderId: '728265546246',
    projectId: 'tupension-e8dae',
    databaseURL: 'https://tupension-e8dae-default-rtdb.firebaseio.com',
    storageBucket: 'tupension-e8dae.appspot.com',
    iosBundleId: 'com.example.tuPension',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6vGlLKlFGCBj3iZkf0OIdh0DXMEFqOFQ',
    appId: '1:728265546246:ios:83a2435b9a781360c4c187',
    messagingSenderId: '728265546246',
    projectId: 'tupension-e8dae',
    databaseURL: 'https://tupension-e8dae-default-rtdb.firebaseio.com',
    storageBucket: 'tupension-e8dae.appspot.com',
    iosBundleId: 'com.example.tuPension.RunnerTests',
  );
}
